SET FOREIGN_KEY_CHECKS=0;
SET AUTOCOMMIT = 0;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS DailyWeights;
DROP TABLE IF EXISTS Equipments;
DROP TABLE IF EXISTS Exercises;
DROP TABLE IF EXISTS BodyParts;
DROP TABLE IF EXISTS ExerciseBodyParts;
DROP TABLE IF EXISTS ExerciseSets;


/*

Create Tables

*/
CREATE TABLE Users (
    user_id int NOT NULL AUTO_INCREMENT,
    firstName varchar(50) NOT NULL,
    birthday date,
    gender varchar(50),
    height varchar(50),
    PRIMARY KEY (user_id)
);

CREATE TABLE DailyWeights (
    weight_id int NOT NULL AUTO_INCREMENT,
    date date NOT NULL,
    weight int NOT NULL,
    user_id int,
    PRIMARY KEY (weight_id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

CREATE TABLE Equipments (
    equipment_id int NOT NULL AUTO_INCREMENT,
    name varchar(255) NOT NULL,
    PRIMARY KEY (equipment_id)
);

CREATE TABLE Exercises (
    exercise_id int NOT NULL AUTO_INCREMENT,
    name varchar(255) NOT NULL,
    notes text,
    equipment_id int,
    PRIMARY KEY (exercise_id),
    FOREIGN KEY (equipment_id) REFERENCES Equipments(equipment_id)
    
);

CREATE TABLE BodyParts (
    bp_id int NOT NULL AUTO_INCREMENT,
    name varchar(255) NOT NULL,
    PRIMARY KEY (bp_id)
);


CREATE TABLE ExerciseBodyParts (
    ebp_id int NOT NULL AUTO_INCREMENT,
    exercise_id int,
    bp_id int,
    PRIMARY KEY (ebp_id),
    FOREIGN KEY (exercise_id) REFERENCES Exercises(exercise_id)
    ON DELETE CASCADE,
    FOREIGN KEY (bp_id) REFERENCES BodyParts(bp_id)
);

CREATE TABLE ExerciseSets (
    es_id int NOT NULL AUTO_INCREMENT,
    date date NOT NULL,
    reps int NOT NULL,
    weight int NOT NULL,
    exercise_id int,
    PRIMARY KEY (es_id),
    FOREIGN KEY (exercise_id) REFERENCES Exercises(exercise_id)
    ON DELETE CASCADE
);

/*

Inserts

*/
INSERT INTO Users(firstName, birthday, gender, height) 
VALUES 
('Simon', '1995-12-29', 'male', "5'9");

INSERT INTO DailyWeights (date, weight, user_id)
VALUES
("2024-01-01", 170, 1),
("2024-01-02", 172, 1),
("2024-01-03", 172, 1),
("2024-01-04", 171, 1),
("2024-01-05", 172, 1),
("2024-01-06", 171, 1),
("2024-01-07", 173, 1),
("2024-01-08", 174, 1),
("2024-01-09", 174, 1),
("2024-01-10", 172, 1),
("2024-01-11", 173, 1),
("2024-01-12", 173, 1),
("2024-01-13", 174, 1),
("2024-01-14", 175, 1),
("2024-01-15", 174, 1),
("2024-01-16", 174, 1),
("2024-01-17", 175, 1),
("2024-01-18", 175, 1),
("2024-01-19", 175, 1),
("2024-01-20", 175, 1),
("2024-01-21", 176, 1),
("2024-01-22", 175, 1),
("2024-01-23", 175, 1),
("2024-01-24", 174, 1),
("2024-01-25", 175, 1),
("2024-01-26", 175, 1),
("2024-01-27", 176, 1),
("2024-01-28", 176, 1),
("2024-01-29", 176, 1),
("2024-01-30", 176, 1),
("2024-01-31", 176, 1),
("2024-02-01", 176, 1),
("2024-02-02", 175, 1),
("2024-02-03", 176, 1),
("2024-02-04", 176, 1),
("2024-02-05", 177, 1),
("2024-02-06", 176, 1),
("2024-02-07", 177, 1),
("2024-02-08", 177, 1),
("2024-02-09", 177, 1),
("2024-02-10", 176, 1),
("2024-02-11", 175, 1),
("2024-02-12", 176, 1),
("2024-02-13", 177, 1),
("2024-02-14", 176, 1),
("2024-02-15", 177, 1),
("2024-02-16", 177, 1),
("2024-02-17", 177, 1),
("2024-02-18", 177, 1),
("2024-02-19", 177, 1),
("2024-02-20", 177, 1),
("2024-02-21", 176, 1),
("2024-02-22", 178, 1),
("2024-02-23", 177, 1),
("2024-02-24", 177, 1),
("2024-02-25", 178, 1),
("2024-02-26", 178, 1),
("2024-02-27", 178, 1),
("2024-02-28", 177, 1),
("2024-02-29", 178, 1),
("2024-03-01", 178, 1),
("2024-03-02", 178, 1),
("2024-03-03", 177, 1),
("2024-03-04", 178, 1),
("2024-03-05", 178, 1),
("2024-03-06", 179, 1),
("2024-03-07", 178, 1),
("2024-03-08", 179, 1),
("2024-03-09", 179, 1),
("2024-03-10", 179, 1),
("2024-03-11", 180, 1),
("2024-03-12", 179, 1),
("2024-03-13", 180, 1),
("2024-03-14", 179, 1),
("2024-03-15", 180, 1),
("2024-03-16", 180, 1),
("2024-03-17", 180, 1);

INSERT INTO Equipments(name) 
VALUES 
("Barbell"),
("Dumbbell"),
("Machine / Other"),
("Bodyweight"),
("Weighted Bodyweight"),
("Assisted Bodyweight"),
("Cardio");

INSERT INTO Exercises(name, equipment_id) 
VALUES 
('Arnold Press', 2),
('Back Extensions', 5),
('Bench Press (Barbell)', 1),
('Bench Press (Dumbbell)', 2),
('Bench Press (Smith Machine)', 3),
('Bench Press - Close Grip (Barbell)', 1),
('Bench Press - Wide Grip (Barbell)', 1),
('Bent Over One Arm Row (Dumbbell)', 2),
('Bent Over Row - Underhand (Barbell)', 1),
('Bent Over Row - Overhand (Barbell)', 1),
('Bent Over Row (Dumbbell)', 2),
('Bicep Curl (Barbell)', 1),
('Bicep Curl (Cable)', 3),
('Bicep Curl (Dumbbell)', 2),
('Bicep Curl (Machine)', 3),
('Cable Crossover', 3),
('Cable Kickback', 3),
('Calf Raise on Leg Press', 3),
('Chest Dip', 4),
('Chest Dip (Assisted)', 3),
('Chest Fly (Cable)', 3),
('Chest Fly (Dumbbell)', 2),
('Chest Fly (Machine)', 3),
('Chest Press (Machine)', 3),
('Chin Up', 4),
('Chin Up (Assisted)', 3),
('Clean', 1),
('Clean and Jerk', 1),
('Climbing', 7),
('Concentration Curl', 2),
('Crunch', 4),
('Cycling', 7),
('Deadlift (Barbell)', 1),
('Deadlift (Dumbbell)', 2),
('Deadlift (Smith Machine)', 3),
('Decline Bench Press (Barbell)', 1),
('Decline Bench Press (Dumbbell)', 2),
('Decline Bench Press (Smith Machine)', 3),
('Decline Crunch', 4),
('Decline Crunch (Weighted)', 5),
('Face Pull', 3),
('Front Raise (Barbell)', 1),
('Front Raise (Cable)', 3),
('Front Raise (Dumbbell)', 2),
('Front Raise (Plate)', 3),
('Front Squat', 1),
('Goblet Squat', 3),
('Good Morning (Barbell)', 1),
('Hack Squats (Barbell)', 1),
('Hack Squats (Machine)', 3),
('Hammer Curl (Band)', 3),
('Hammer Curl (Cable)', 3),
('Hammer Curl (Dumbbell)', 2),
('Hang Clean (Barbell)', 1),
('Hang Snatch (Barbell)', 1),
('Hanging Knee Raise', 4),
('Hanging Leg Raise', 4),
('Hip Abductor (Machine)', 3),
('Hip Adductor (Machine)', 3),
('Hip Thrust (Barbell)', 1),
('Hip Thrust (Bodyweight)', 4),
('Hip Thrust (Machine)', 3),
('Incline Bench Press (Barbell)', 1),
('Incline Bench Press (Cable)', 3),
('Incline Bench Press (Dumbbell)', 2),
('Incline Bench Press (Smith Machine)', 3),
('Incline Chest Fly (Dumbbell)', 2),
('Incline Chest Press (Machine)', 3),
('Incline Curl (Dumbbell)', 2),
('Incline Row (Dumbbell)', 2),
('Inverted Row (Bodyweight)', 4),
('Lat Pulldown (Cable)', 3),
('Lat Pulldown (Machine)', 3),
('Lat Pulldown - Close Grip (Machine)', 3),
('Lat Pulldown - Wide Grip (Machine)', 3),
('Lateral Raise (Cable)', 3),
('Lateral Raise (Dumbbell)', 2),
('Lateral Raise (Machine)', 3),
('Leg Extension', 3),
('Leg Press', 3),
('Lunge (Barbell)', 1),
('Lunge (Bodyweight)', 4),
('Lunge (Dumbbell)', 2),
('Lying Leg Curl', 3),
('Muscle Up', 4),
('Overhead Press (Barbell)', 1),
('Overhead Press (Cable)', 3),
('Overhead Press (Dumbbell)', 2),
('Overhead Press (Smith Machine)', 3),
('Overhead Squat', 1),
('Pec Deck', 3),
('Pistol Squat', 4),
('Plank', 4),
('Preacher Curl (Barbell)', 1),
('Preacher Curl (Dumbbell)', 2),
('Preacher Curl (Machine)', 3),
('Pull Up', 4),
('Pull Up (Assisted)', 6),
('Push Up', 4),
('Rack Pull', 1),
('Reverse Fly (Cable)', 3),
('Reverse Fly (Dumbbell)', 2),
('Reverse Fly (Machine)', 3),
('Romanian Deadlift (Barbell)', 1),
('Romanian Deadlift (Dumbbell)', 2),
('Seated Calf Raise (Plate)', 3),
('Seated Leg Curl', 3),
('Seated Overhead Press (Barbell)', 1),
('Seated Overhead Press (Dumbbell)', 2),
('Seated Row (Cable)', 3),
('Seated Row (Machine)', 3),
('Squat (Barbell)', 1),
('Squat (Bodyweight)', 4),
('Squat (Dumbbell)', 2),
('Squat (Machine)', 3),
('Squat (Smith Machine)', 3),
('Standing Calf Raise', 4),
('Tricep Extension (Cable)', 3);

INSERT INTO BodyParts(name)
VALUES
("Biceps"),
("Triceps"),
("Core"),
("Chest"),
("Back"),
("Shoulders"),
("Legs"),
("Full Body"),
("Cardio"),
("Other");

INSERT INTO ExerciseBodyParts(exercise_id, bp_id)
VALUES
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press (Barbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press (Barbell)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press (Barbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press (Dumbbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press (Dumbbell)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press (Dumbbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press (Smith Machine)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press (Smith Machine)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press (Smith Machine)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press - Close Grip (Barbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press - Close Grip (Barbell)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press - Close Grip (Barbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press - Wide Grip (Barbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press - Wide Grip (Barbell)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bench Press - Wide Grip (Barbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bent Over Row - Underhand (Barbell)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bent Over Row - Underhand (Barbell)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bent Over Row - Overhand (Barbell)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bent Over Row - Overhand (Barbell)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bent Over Row (Dumbbell)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bent Over Row (Dumbbell)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bicep Curl (Barbell)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bicep Curl (Cable)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bicep Curl (Dumbbell)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Bicep Curl (Machine)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Cable Crossover"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Cable Kickback"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Calf Raise on Leg Press"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chest Dip"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chest Dip"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chest Dip (Assisted)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chest Dip (Assisted)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chest Fly (Cable)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chest Fly (Dumbbell)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chest Fly (Machine)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chest Press (Machine)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chest Press (Machine)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chin Up"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chin Up"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chin Up (Assisted)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Chin Up (Assisted)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Clean"), 8),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Clean and Jerk"), 8),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Climbing"), 9),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Concentration Curl"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Crunch"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Cycling"), 9),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Deadlift (Barbell)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Deadlift (Barbell)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Deadlift (Barbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Deadlift (Dumbbell)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Deadlift (Dumbbell)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Deadlift (Dumbbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Deadlift (Smith Machine)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Deadlift (Smith Machine)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Deadlift (Smith Machine)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Decline Bench Press (Barbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Decline Bench Press (Barbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Decline Bench Press (Dumbbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Decline Bench Press (Dumbbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Decline Bench Press (Smith Machine)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Decline Bench Press (Smith Machine)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Decline Crunch"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Decline Crunch (Weighted)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Face Pull"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Face Pull"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Front Raise (Barbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Front Raise (Cable)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Front Raise (Dumbbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Front Raise (Plate)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Front Squat"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Front Squat"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Goblet Squat"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Good Morning (Barbell)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Good Morning (Barbell)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hack Squats (Barbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hack Squats (Machine)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hammer Curl (Band)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hammer Curl (Cable)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hammer Curl (Dumbbell)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hang Clean (Barbell)"), 8),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hang Snatch (Barbell)"), 8),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hanging Knee Raise"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hanging Leg Raise"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hip Abductor (Machine)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hip Adductor (Machine)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hip Thrust (Barbell)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hip Thrust (Barbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hip Thrust (Bodyweight)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hip Thrust (Bodyweight)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hip Thrust (Machine)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Hip Thrust (Machine)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Bench Press (Barbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Bench Press (Barbell)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Bench Press (Cable)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Bench Press (Cable)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Bench Press (Dumbbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Bench Press (Dumbbell)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Bench Press (Smith Machine)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Bench Press (Smith Machine)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Chest Fly (Dumbbell)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Chest Fly (Machine)"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Curl (Dumbbell)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Row (Dumbbell)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Incline Row (Dumbbell)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Inverted Row (Bodyweight)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lat Pulldown (Cable)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lat Pulldown (Machine)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lat Pulldown - Close Grip (Machine)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lat Pulldown - Wide Grip (Machine)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lateral Raise (Cable)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lateral Raise (Dumbbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lateral Raise (Machine)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Leg Extension"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Leg Press"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lunge (Barbell)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lunge (Barbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lunge (Bodyweight)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lunge (Bodyweight)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lunge (Dumbbell)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lunge (Dumbbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Lying Leg Curl"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Muscle Up"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Muscle Up"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Overhead Press (Barbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Overhead Press (Barbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Overhead Press (Cable)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Overhead Press (Cable)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Overhead Press (Dumbbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Overhead Press (Dumbbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Overhead Press (Smith Machine)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Overhead Press (Smith Machine)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Overhead Squat"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Overhead Squat"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Pec Deck"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Pistol Squat"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Plank"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Preacher Curl (Barbell)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Preacher Curl (Dumbbell)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Preacher Curl (Machine)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Pull Up"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Pull Up (Assisted)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Push Up"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Push Up"), 4),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Rack Pull"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Rack Pull"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Reverse Fly (Cable)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Reverse Fly (Cable)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Reverse Fly (Dumbbell)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Reverse Fly (Dumbbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Reverse Fly (Machine)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Reverse Fly (Machine)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Romanian Deadlift (Barbell)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Romanian Deadlift (Barbell)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Romanian Deadlift (Barbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Romanian Deadlift (Dumbbell)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Romanian Deadlift (Dumbbell)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Romanian Deadlift (Dumbbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Seated Calf Raise (Plate)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Seated Leg Curl"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Seated Overhead Press (Barbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Seated Overhead Press (Barbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Seated Overhead Press (Dumbbell)"), 2),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Seated Overhead Press (Dumbbell)"), 6),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Seated Row (Cable)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Seated Row (Cable)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Seated Row (Machine)"), 1),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Seated Row (Machine)"), 5),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Squat (Barbell)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Squat (Barbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Squat (Bodyweight)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Squat (Bodyweight)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Squat (Dumbbell)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Squat (Dumbbell)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Squat (Machine)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Squat (Machine)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Squat (Smith Machine)"), 3),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Squat (Smith Machine)"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Standing Calf Raise"), 7),
((SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Tricep Extension (Cable)"), 2);

INSERT INTO ExerciseSets(date, exercise_id, reps, weight)
VALUES 
("2024-02-01", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 30),
("2024-02-01", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 30),
("2024-02-01", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 9, 30),
("2024-02-01", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 20),
("2024-02-01", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 20),
("2024-02-01", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 20),
("2024-02-08", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 35),
("2024-02-08", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 35),
("2024-02-08", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 8, 35),
("2024-02-08", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 20),
("2024-02-08", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 25),
("2024-02-08", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 8, 25),
("2024-02-16", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 35),
("2024-02-16", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 35),
("2024-02-16", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 35),
("2024-02-16", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 25),
("2024-02-16", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 25),
("2024-02-16", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 25),
("2024-02-22", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 8, 40),
("2024-02-22", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 8, 40),
("2024-02-22", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 8, 40),
("2024-02-22", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 25),
("2024-02-22", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 25),
("2024-02-22", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 30),
("2024-02-28", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 9, 40),
("2024-02-28", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 9, 40),
("2024-02-28", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 9, 40),
("2024-02-28", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 30),
("2024-02-28", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 30),
("2024-02-28", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 30),
("2024-03-05", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 40),
("2024-03-05", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 40),
("2024-03-05", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 40),
("2024-03-05", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 30),
("2024-03-05", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 30),
("2024-03-05", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 30),
("2024-03-11", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 8, 45),
("2024-03-11", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 8, 45),
("2024-03-11", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Arnold Press"), 10, 40),
("2024-03-11", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 12, 30),
("2024-03-11", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 30),
("2024-03-11", (SELECT Exercises.exercise_id FROM Exercises WHERE Exercises.name = "Back Extensions"), 10, 30);

SET FOREIGN_KEY_CHECKS=1;
COMMIT;