INSERT INTO Exercises(name, equipment_id) 
VALUES 
('Arnold Press', 2),
('Back Extensions', 5),
('Bench Press (Barbell)', 1),
('Bench Press (Dumbbell)', 2),
('Bench Press (Smith Machine)', 3),
('Bench Press - Close Grip (Barbell)', 1),
('Bench Press - Wide Grip (Barbell)', 1),
('Bent Over One Arm Row (Dumbbell)', 2),
('Bent Over Row - Underhand (Barbell)', 1),
('Bent Over Row - Overhand (Barbell)', 1),
('Bent Over Row (Dumbbell)', 2),
('Bicep Curl (Barbell)', 1),
('Bicep Curl (Cable)', 3),
('Bicep Curl (Dumbbell)', 2),
('Bicep Curl (Machine)', 3),
('Cable Crossover', 3),
('Cable Kickback', 3),
('Calf Raise on Leg Press', 3),
('Chest Dip', 4),
('Chest Dip (Assisted)', 3),
('Chest Fly (Cable)', 3),
('Chest Fly (Dumbbell)', 2),
('Chest Fly (Machine)', 3),
('Chest Press (Machine)', 3),
('Chin Up', 4),
('Chin Up (Assisted)', 3),
('Clean', 1),
('Clean and Jerk', 1),
('Climbing', 7),
('Concentration Curl', 2),
('Crunch', 4),
('Cycling', 7),
('Deadlift (Barbell)', 1),
('Deadlift (Dumbbell)', 2),
('Deadlift (Smith Machine)', 3),
('Decline Bench Press (Barbell)', 1),
('Decline Bench Press (Dumbbell)', 2),
('Decline Bench Press (Smith Machine)', 3),
('Decline Crunch', 4),
('Decline Crunch (Weighted)', 5),
('Face Pull', 3),
('Front Raise (Barbell)', 1),
('Front Raise (Cable)', 3),
('Front Raise (Dumbbell)', 2),
('Front Raise (Plate)', 3),
('Front Squat', 1),
('Goblet Squat', 3),
('Good Morning (Barbell)', 1),
('Hack Squats (Barbell)', 1),
('Hack Squats (Machine)', 3),
('Hammer Curl (Band)', 3),
('Hammer Curl (Cable)', 3),
('Hammer Curl (Dumbbell)', 2),
('Hang Clean (Barbell)', 1),
('Hang Snatch (Barbell)', 1),
('Hanging Knee Raise', 4),
('Hanging Leg Raise', 4),
('Hip Abductor (Machine)', 3),
('Hip Adductor (Machine)', 3),
('Hip Thrust (Barbell)', 1),
('Hip Thrust (Bodyweight)', 4),
('Hip Thrust (Machine)', 3),
('Incline Bench Press (Barbell)', 1),
('Incline Bench Press (Cable)', 3),
('Incline Bench Press (Dumbbell)', 2),
('Incline Bench Press (Smith Machine)', 3),
('Incline Chest Fly (Dumbbell)', 2),
('Incline Chest Press (Machine)', 3),
('Incline Curl (Dumbbell)', 2),
('Incline Row (Dumbbell)', 2),
('Inverted Row (Bodyweight)', 4),
('Lat Pulldown (Cable)', 3),
('Lat Pulldown (Machine)', 3),
('Lat Pulldown - Close Grip (Machine)', 3),
('Lat Pulldown - Wide Grip (Machine)', 3),
('Lateral Raise (Cable)', 3),
('Lateral Raise (Dumbbell)', 2),
('Lateral Raise (Machine)', 3),
('Leg Extension', 3),
('Leg Press', 3),
('Lunge (Barbell)', 1),
('Lunge (Bodyweight)', 4),
('Lunge (Dumbbell)', 2),
('Lying Leg Curl', 3),
('Muscle Up', 4),
('Overhead Press (Barbell)', 1),
('Overhead Press (Cable)', 3),
('Overhead Press (Dumbbell)', 2),
('Overhead Press (Smith Machine)', 3),
('Overhead Squat', 1),
('Pec Deck', 3),
('Pistol Squat', 4),
('Plank', 4),
('Preacher Curl (Barbell)', 1),
('Preacher Curl (Dumbbell)', 2),
('Preacher Curl (Machine)', 3),
('Pull Up', 4),
('Pull Up (Assisted)', 6),
('Push Up', 4),
('Rack Pull', 1),
('Reverse Fly (Cable)', 3),
('Reverse Fly (Dumbbell)', 2),
('Reverse Fly (Machine)', 3),
('Romanian Deadlift (Barbell)', 1),
('Romanian Deadlift (Dumbbell)', 2),
('Seated Calf Raise (Plate)', 3),
('Seated Leg Curl', 3),
('Seated Overhead Press (Barbell)', 1),
('Seated Overhead Press (Dumbbell)', 2),
('Seated Row (Cable)', 3),
('Seated Row (Machine)', 3),
('Squat (Barbell)', 1),
('Squat (Bodyweight)', 4),
('Squat (Dumbbell)', 2),
('Squat (Machine)', 3),
('Squat (Smith Machine)', 3),
('Standing Calf Raise', 4),
('Tricep Extension (Cable)', 3);

COMMIT;
